### PR TITLE
Update to POMDPs 0.9 and refine the implementation

### PR DESCRIPTION
**Pull request by Wu-Chenyang**
I updated this package to support POMDPs 0.9 and made some other changes to make it run significantly faster.
The changes include:
- make global variables constants
- replace small vectors with StaticArray
- replace disposable vectors with loops
- make functions type-stable
- avoid type judgment within a function (if different types require different treatments, separate the function via multiple dispatches)
- speed up `stateindex` by removing `LinearIndices`
- replace both `LidarResampler` and `BumperResampler` with `LowVarianceResampler`

### CODE REVIEW

**Comment by Wu-Chenyang** [comment]
Besides, I want to cite this domain in a paper, how to cite it properly? :)

**Comment by mykelk** [comment]
Awesome! Thanks so much! It looks like there is a build error due to versioning. Would you mind taking a stab at addressing that? Probably the best way to cite this domain is to give a link to the repo. Perhaps in the future, we can package up the environment portion of it and post in the JuliaPOMDPs repo. @zsunberg do you have any thoughts on this?

**Comment by Wu-Chenyang** [comment]
I think the build error is caused by the misspecified version of Julia in Travis. I will fix it.

**Comment by mykelk** [comment]
Thanks so much!

**Comment by zsunberg** [comment]
Thank you @Wu-Chenyang !!

> @zsunberg do you have any thoughts on this?

It is already in the POMDPGallery repo, and that is the closest thing we have right now to a list of environment repos. Maybe we should organize environments in some other way in the future.

It would be a good contribution to change the name of the package to reflect that it is a roomba environment and change the README to be more focused on how to use the environment rather than details of how to install it, but it is already fairly usable as is.

**Pull request merged**
